### ISSUE TITLE
Remove small switches?

### ISSUE THREAD

**Issue by coliff** [trimble-oss/website-modus-bootstrap.trimble.com#178]
heya @egunther39 - we have small switches on Sample page:
https://modus-bootstrap.trimble.com/sample-page/next/#switches

![image](https://user-images.githubusercontent.com/1212885/185428697-5eea49f9-5724-41a9-b7ce-b3b548a8a97f.png)

But they aren't documented in style guide or Modus Bootstrap site? Should they be removed?

**Comment by egunther39** [comment]
Please remove

**Comment by coliff** [comment]
Removed! This change will be in the next release.
https://bitbucket.trimble.tools/projects/TMDS/repos/modus-bootstrap/pull-requests?state=MERGED&reviewer=
