### ISSUE TITLE
Date Picker in Bootstrap

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/website-modus-bootstrap.trimble.com#226]
we recommend a third-party one rather than building it from scratch ourselves. e.g.
- https://github.com/duetds/date-picker
- https://easepick.com/
- Trimble Maps Developers created a 'Modus Date Range Picker'. (https://npm.trimblemaps.com/-/web/detail/modus-date-range-picker) - you need to login to see
- There is also an Angular Bootstrap Datepicker (https://valor-software.com/ngx-bootstrap/#/components/datepicker?tab=overview)

**Comment by msankaran0712** [comment]
@coliff, any updates?

**Comment by coliff** [comment]
was thinking of adding a simple page like this:

![image](https://github.com/trimble-oss/website-modus-bootstrap.trimble.com/assets/1212885/892260d9-8800-49cb-bf30-675c4012320d)
