### ISSUE TITLE
Bug: No hover background for Navbar icons

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/website-modus-bootstrap.trimble.com#265]
### Describe the issue

![chrome_TXuSEHMJwc](https://user-images.githubusercontent.com/50131391/211736862-909eb711-fc30-4886-b460-d4e2f7638942.gif)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

**Comment by coliff** [comment]
Thanks for repotting this issue. Comparing it to the icon buttons here: https://modus-bootstrap.trimble.com/components/buttons/#icon-only-buttons - it looks like the `btn-text-dark` or `btn-text-secondary` CSS class is needed.

**Comment by coliff** [comment]
yep, adding that class works! I'll make a PR for it later today.

https://codepen.io/coliff/pen/gOjWORp
