### ISSUE TITLE
Add an example with helper text on large inputs to Bootstrap

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/website-modus-bootstrap.trimble.com#275]
32 px input helper text 11 px semibold, 48 px input helper text 12 px semibold

**Comment by coliff** [comment]
Could you please provide more details and specs on this request.
Are changes need to Modus Bootstrap or did you mean just add an example like the second one in this Codepen?
https://codepen.io/coliff/pen/LYJYXKO

**Comment by soniakaukonen** [comment]
@coliff  There was a font size change (font size was universally 10.5 regular and perceived too small). The final decision was 11px semibold for 32px inputs and 12px semibold for 48px inputs, so would require a change (and an example). We are in process of updating the UI kits. However, considering longer help text, I would still like to review the semibold weight of the text if that might not be too dominating.

**Comment by coliff** [comment]
Example demo updated here to preview with font-weight:600. The first one is font-size:11px (down from 12px) and the second is 12px. We don't use 11px anywhere else at all.
Personally, I think it looks a bit too small and preferred it being 12px. (12px is the default 'small' size).
