### ISSUE TITLE
Fix Shadow Color

### ISSUE THREAD

**Issue by egunther39** [trimble-oss/website-modus-bootstrap.trimble.com#285]
Shadow color is listed as `rgba(36,35,45,.3)`
When converting rgb to hex, the value is `#24232D` which is not a Modus color.

Please change shadow color to Trimble Gray  `rgba(37,42,46,.3)`

**Comment by coliff** [comment]
I can fix the shadow utility classes with this change to `_modus-variables.scss`

```scss
$box-shadow-sm: 0 0 2px rgba(37, 42, 46, 0.3) !default;
$box-shadow: 0 0 4px rgba(37, 42, 46, 0.3) !default;
$box-shadow-lg: 0 0 8px rgba(37, 42, 46, 0.3) !default;
```

**Comment by coliff** [comment]
Fixed in: https://bitbucket.trimble.tools/projects/TMDS/repos/modus-bootstrap/pull-requests/289/overview
