### ISSUE TITLE
Accordion Header/Button doesn't have hover state (Light Mode)

### ISSUE THREAD

**Issue by coliff** [trimble-oss/website-modus-bootstrap.trimble.com#291]
The header/button should have background color `#e0e1e9` on hover.

**Comment by coliff** [comment]
PR Created: https://bitbucket.trimble.tools/projects/TMDS/repos/modus-bootstrap/pull-requests/293/overview

**Comment by msankaran0712** [comment]
Looking at the PR I think it will automatically fix it in React too
