### ISSUE TITLE
Change Tooltip Background color (Dark Mode)

### ISSUE THREAD

**Issue by coliff** [trimble-oss/website-modus-bootstrap.trimble.com#304]
Change Tooltip background color to Gray 4 `#90939f`

(reference: https://github.com/trimble-oss/website-modus.trimble.com/issues/477#issuecomment-1480734756)

**Comment by soniakaukonen** [comment]
New decision 3/31/2023:

Due to accessibility issues, change for dark mode tooltip to: 

background Gray 0 (#E0E1E9), 
text: Trimble Gray (#252A2E) 

as below:



![Image](https://user-images.githubusercontent.com/101354258/229162594-da561ada-dd80-44c6-88d5-984051b48533.png)

**Comment by coliff** [comment]
This is fixed in Modus Bootstrap and will be included in the next release, v1.5.7. The site will update then.
