### ISSUE TITLE
Modus Bootstrap - New graphics for Error page

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/website-modus-bootstrap.trimble.com#330]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/website-modus-bootstrap.trimble.com/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/website-modus-bootstrap.trimble.com/blob/main/.github/CONTRIBUTING.md)

### Proposal

Get the images from Ewa or Christian

### Motivation and context

Update graphics

**Comment by coliff** [comment]
Do you have the graphics for this? Happy to add them if so...

**Comment by coliff** [comment]
@enowak1031 - Do you have the graphics for this? Happy to add them if so...
