### ISSUE TITLE
Current Tab Text should be blue (dark mode)

### ISSUE THREAD

**Issue by coliff** [trimble-oss/website-modus-bootstrap.trimble.com#347]
### Describe the issue

Modus Bootstrap's tabs in dark mode currently have white text for the current page.
https://modus.trimble.com/components/web/tabs/

![image](https://github.com/trimble-oss/website-modus-bootstrap.trimble.com/assets/1212885/41439d65-ac27-45b8-8479-9380b7613a58)

The text should be blue to match the Figma design
![image](https://github.com/trimble-oss/website-modus-bootstrap.trimble.com/assets/1212885/48a1901b-179c-4b63-b67e-be06ce586048)

cc @soniakaukonen @egunther39 - please correct me If I'm wrong in this assumption. It's not 100% clear because the Figma design has Active, Default, Hover and Disabled states, but I'm referencing the **current** page which isn't technically 'active' in that it isn't being interacted with (clicked).

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

**Comment by soniakaukonen** [comment]
@coliff @egunther39 

A good catch. Yes, selected is both on Figma and XD blue (highlight blue) text underlined blue (highlight blue) in dark mode. The question is do we even distinguished between those states, "current but not interacted with" vs. active? On the side note, the component improvement tigers are wrapping up soon so will be redefined anyway and this state was one of the most problematic to be recognized in tabs.

**Comment by soniakaukonen** [comment]
PS. The not so great thing is that light mode is correct, just in dark mode the text does not follow the kits.

**Comment by coliff** [comment]
Yes, it should be blue and the fact is isn't right now is a CSS bug (white color overriding it) which I'm fixing now.

**Comment by coliff** [comment]
PR merged. Will be part of the next release of Modus Bootstrap.
