### ISSUE TITLE
Primary Button Hover state color not Modus compliant

### ISSUE THREAD

**Issue by jmecosta** [trimble-oss/website-modus-bootstrap.trimble.com#368]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-react-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have validated any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-react-bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

<img width="631" alt="image" src="https://github.com/trimble-oss/modus-react-bootstrap/assets/1041352/77b6ae99-a89d-427e-939a-dd4db933f142">

### Reduced test cases

none

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Modus React Bootstrap are you using?

1

### Priority

Low

**Comment by msankaran0712** [comment]
@coliff can you please assign a sprint and story points?

**Comment by coliff** [comment]
Fixed in: https://bitbucket.trimble.tools/projects/TMDS/repos/modus-bootstrap/pull-requests/320/overviewand will be included in the next release.
