### ISSUE TITLE
Compact Progress Bar

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/website-modus-bootstrap.trimble.com#89]
As a user of the design system, I want to have a compact progress bar option available, so I can use it where the space is limited and where the focus should not be taken away from the other components in the interface. 

A standard progress bar is 16px height. We should add a small variant which is half the height.
https://modus.trimble.com/components/progress-bars/

**Comment by coliff** [comment]
PR is open for this:
https://bitbucket.trimble.tools/projects/TMDS/repos/modus-bootstrap/pull-requests/247/overview

**Comment by coliff** [comment]
This is merged now and will ship in the next release.
